export interface Database {
  public: {
    Tables: {
      organizations: {
        Row: {
          id: string;
          name: string;
          domain: string;
          industry: string | null;
          website_url: string | null;
          plan_type: string;
          status: string;
          user_limit: number;
          storage_limit_gb: number;
          api_calls_limit: number;
          settings: Record<string, any>;
          branding: Record<string, any>;
          created_at: string;
          updated_at: string;
          created_by: string | null;
        };
        Insert: {
          id?: string;
          name: string;
          domain: string;
          industry?: string | null;
          website_url?: string | null;
          plan_type?: string;
          status?: string;
          user_limit?: number;
          storage_limit_gb?: number;
          api_calls_limit?: number;
          settings?: Record<string, any>;
          branding?: Record<string, any>;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
        };
        Update: {
          id?: string;
          name?: string;
          domain?: string;
          industry?: string | null;
          website_url?: string | null;
          plan_type?: string;
          status?: string;
          user_limit?: number;
          storage_limit_gb?: number;
          api_calls_limit?: number;
          settings?: Record<string, any>;
          branding?: Record<string, any>;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
        };
      };
      users: {
        Row: {
          id: string;
          email: string;
          first_name: string | null;
          last_name: string | null;
          role: string;
          organization_id: string | null;
          avatar_url: string | null;
          phone_number: string | null;
          job_title: string | null;
          department: string | null;
          status: string;
          is_verified: boolean;
          email_verified_at: string | null;
          timezone: string;
          language: string;
          preferences: Record<string, any>;
          created_at: string;
          updated_at: string;
          last_login_at: string | null;
          created_by: string | null;
        };
        Insert: {
          id: string;
          email: string;
          first_name?: string | null;
          last_name?: string | null;
          role?: string;
          organization_id?: string | null;
          avatar_url?: string | null;
          phone_number?: string | null;
          job_title?: string | null;
          department?: string | null;
          status?: string;
          is_verified?: boolean;
          email_verified_at?: string | null;
          timezone?: string;
          language?: string;
          preferences?: Record<string, any>;
          created_at?: string;
          updated_at?: string;
          last_login_at?: string | null;
          created_by?: string | null;
        };
        Update: {
          id?: string;
          email?: string;
          first_name?: string | null;
          last_name?: string | null;
          role?: string;
          organization_id?: string | null;
          avatar_url?: string | null;
          phone_number?: string | null;
          job_title?: string | null;
          department?: string | null;
          status?: string;
          is_verified?: boolean;
          email_verified_at?: string | null;
          timezone?: string;
          language?: string;
          preferences?: Record<string, any>;
          created_at?: string;
          updated_at?: string;
          last_login_at?: string | null;
          created_by?: string | null;
        };
      };
      access_requests: {
        Row: {
          id: string;
          email: string;
          first_name: string;
          last_name: string;
          phone_number: string | null;
          job_title: string | null;
          organization_name: string;
          organization_domain: string | null;
          organization_size: string | null;
          industry: string | null;
          business_description: string | null;
          use_case: string;
          expected_users: number | null;
          technical_requirements: string | null;
          requested_plan: string;
          urgency: string;
          stage: string;
          status: string;
          initial_reviewer_id: string | null;
          initial_review_notes: string | null;
          initial_reviewed_at: string | null;
          technical_reviewer_id: string | null;
          technical_review_notes: string | null;
          technical_reviewed_at: string | null;
          business_reviewer_id: string | null;
          business_review_notes: string | null;
          business_reviewed_at: string | null;
          final_approver_id: string | null;
          final_approval_notes: string | null;
          final_approved_at: string | null;
          rejection_reason: string | null;
          rejected_by: string | null;
          rejected_at: string | null;
          assigned_organization_id: string | null;
          assigned_plan: string | null;
          source: string | null;
          referral_code: string | null;
          metadata: Record<string, any>;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          email: string;
          first_name: string;
          last_name: string;
          phone_number?: string | null;
          job_title?: string | null;
          organization_name: string;
          organization_domain?: string | null;
          organization_size?: string | null;
          industry?: string | null;
          business_description?: string | null;
          use_case: string;
          expected_users?: number | null;
          technical_requirements?: string | null;
          requested_plan?: string;
          urgency?: string;
          stage?: string;
          status?: string;
          initial_reviewer_id?: string | null;
          initial_review_notes?: string | null;
          initial_reviewed_at?: string | null;
          technical_reviewer_id?: string | null;
          technical_review_notes?: string | null;
          technical_reviewed_at?: string | null;
          business_reviewer_id?: string | null;
          business_review_notes?: string | null;
          business_reviewed_at?: string | null;
          final_approver_id?: string | null;
          final_approval_notes?: string | null;
          final_approved_at?: string | null;
          rejection_reason?: string | null;
          rejected_by?: string | null;
          rejected_at?: string | null;
          assigned_organization_id?: string | null;
          assigned_plan?: string | null;
          source?: string | null;
          referral_code?: string | null;
          metadata?: Record<string, any>;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          first_name?: string;
          last_name?: string;
          phone_number?: string | null;
          job_title?: string | null;
          organization_name?: string;
          organization_domain?: string | null;
          organization_size?: string | null;
          industry?: string | null;
          business_description?: string | null;
          use_case?: string;
          expected_users?: number | null;
          technical_requirements?: string | null;
          requested_plan?: string;
          urgency?: string;
          stage?: string;
          status?: string;
          initial_reviewer_id?: string | null;
          initial_review_notes?: string | null;
          initial_reviewed_at?: string | null;
          technical_reviewer_id?: string | null;
          technical_review_notes?: string | null;
          technical_reviewed_at?: string | null;
          business_reviewer_id?: string | null;
          business_review_notes?: string | null;
          business_reviewed_at?: string | null;
          final_approver_id?: string | null;
          final_approval_notes?: string | null;
          final_approved_at?: string | null;
          rejection_reason?: string | null;
          rejected_by?: string | null;
          rejected_at?: string | null;
          assigned_organization_id?: string | null;
          assigned_plan?: string | null;
          source?: string | null;
          referral_code?: string | null;
          metadata?: Record<string, any>;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
  };
}